const Elements = {
    page: document.querySelector(".page"),
    header: document.querySelector(".header"),
    startpage: document.querySelector(".start-page"),
    weatherpage: document.querySelector(".weather-page"),
    weatherPage__previewblock: document.querySelector(".weather-page__previewblock"),
    weatherPage__previewblockInfoBg: document.querySelector(".weather-page__previewblock-info-bg"),
    weatherPage__topblockTitleblockTitle: document.querySelector(".weather-page__topblock-titleblock-title"),
    weatherPage__topblockTitleblockDate: document.querySelector(".weather-page__topblock-titleblock-date"),
    weatherPage__topblockTime: document.querySelector(".weather-page__topblock-time"),
    weatherPage__botblockDegrees: document.querySelector(".weather-page__botblock-degrees"),
    weatherPage__botblockAvgdegrees: document.querySelector(".weather-page__botblock-avgdegrees"),
    weatherPage__botblockText: document.querySelector(".weather-page__botblock-text"),
    weatherPage__previewblockInfoDecor: document.querySelector(".weather-page__previewblock-info-decor"),
    weatherPage__infoblocksToday: document.querySelector(".weather-page__infoblocks-today"),
    weatherPage__detailsValue_thermalSensation: document.querySelector(".weather-page__details-value_thermal-sensation"),
    weatherPage__detailsValue_visibility: document.querySelector(".weather-page__details-value_visibility"),
    weatherPage__detailsValue_windSpeed: document.querySelector(".weather-page__details-value_wind-speed"),
    weatherPage__detailsValue_airHumidity: document.querySelector(".weather-page__details-value_air-humidity"),
    weatherPage__detailsValue_airPollution: document.querySelector(".weather-page__details-value_airPollution"),
    weatherPage__infoblocksNextdays: document.querySelector(".weather-page__infoblocks-nextdays"),
    weatherBlocks: document.querySelectorAll(".weather-page__block"),
    wrapper: document.querySelector(".wrapper"),
    inputElemWeather: document.querySelector(".weather-page__input"),
    inputElemStart: document.querySelector('.start-page__inputblock-input'),
    weatherPage__logo: document.getElementById("weather-page__logo"),
    loader: document.getElementById("loader"),
    notfoundBlock: document.querySelector(".start-page__notfound"),
}

export default Elements