name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v4
    - run: npm run build --env.NODE_ENV=production
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './dist'
