name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v4
    - name: Install dependencies
      run: npm install
    - name: Webpack build
      run: npx webpack --env=production
      env: 
        WEATHERAPIKEY: ${{ secrets.WEATHERAPIKEY }}
        WEATHERAPIKEY2: ${{ secrets.WEATHERAPIKEY2 }}
    - name: Deploy to custom branch
      run: |
        git checkout -b gh-pages
        git add .
        git commit -m "Deploy to gh-pages branch"
        git push origin gh-pages
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './dist'
        branch: gh-pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
        
