name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cypress tests
      uses: ./
      with:
        working-directory: examples/webpack
        start: npm start
        wait-on: 'http://localhost:8080'
